-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, A.TOTAL_SALES FROM(
            SELECT A.AUTHOR_ID, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
            FROM BOOK A, BOOK_SALES C
            WHERE 1=1
            AND A.BOOK_ID = C.BOOK_ID
            AND TO_CHAR(C.SALES_DATE, 'YYYYMM') = '202201'
            GROUP BY A.AUTHOR_ID, A.CATEGORY
        ) A, AUTHOR B
WHERE 1=1
AND A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY AUTHOR_ID, CATEGORY DESC
