SELECT TO_CHAR(SALES_DATE, 'YYYY') AS YEAR
    ,TO_NUMBER(TO_CHAR(SALES_DATE, 'MM')) AS MONTH
    ,GENDER
    ,count(DISTINCT a.USER_ID) AS USERS
FROM USER_INFO a, ONLINE_SALE b
WHERE 1=1
AND a.USER_ID = b.USER_ID
AND GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE, 'YYYY'), TO_CHAR(SALES_DATE, 'MM'), GENDER
ORDER BY 1, 2, 3