-- 코드를 입력하세요
SELECT * FROM (
        SELECT A.FLAVOR
        FROM FIRST_HALF A, JULY B
        WHERE A.FLAVOR = B.FLAVOR
        GROUP BY A.FLAVOR
        ORDER BY SUM(A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
    )
WHERE ROWNUM BETWEEN 0 AND 3